image: mysql:latest

stages:
  - deploy

variables:
  MYSQL_HOST: mysql-rfampublic.ebi.ac.uk
  MYSQL_PORT: 4497
  MYSQL_DATABASE: Rfam
  MYSQL_USER: rfamro
  MYSQL_PASSWORD: none 

deploy:
  stage: deploy
  script:
    - mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < script.sql
  only:
    changes:
      - script.sql
